export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const OPEN_CART = 'OPEN_CART';
export const CLOSE_CART = 'CLOSE_CART';
export const TOGGLE_BASIC_FILTER = 'TOGGLE_BASIC_FILTER';
export const CHANGE_PRICE_FILTER = 'CHANGE_PRICE_FILTER';
export const CHANGE_SORT = 'CHANGE_SORT';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
